FROM node:23-alpine AS builder

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias completas para build
RUN npm ci

# Copiar código fuente
COPY . .

# Construir la aplicación
RUN npm run build

# Eliminar devDependencies
RUN npm prune --production

# Etapa de producción
FROM node:23-alpine AS production

WORKDIR /app

# Crear usuario no-root
# RUN addgroup -g 1001 -S nodejs && adduser -S nestjs -u 1001

# Crear directorio de logs
# RUN mkdir -p /app/logs && chown -R nestjs:nodejs /app && chmod -R 775 /app/logs

# Copiar solo lo necesario
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

# Cambiar usuario
# USER nestjs

EXPOSE 3000

CMD ["node", "dist/main"]